apiVersion: v1
kind: Service
metadata:
  name:  concourse-rtp-service
  namespace: concourse
spec:
  type: NodePort
  selector:
    app: concourse-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000